spring.application.name=stele

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=temppass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Multipart file upload settings (5MB limit)
spring.servlet.multipart.max-file-size=${image.maxFileSizeMB:5}MB
spring.servlet.multipart.max-request-size=${image.maxFileSizeMB:5}MB